---

#almalinux8 - almalinux9
#java-17-openjdk

#centos7
#java-latest-openjdk

- name: Install openjdk18 on Centos7
  package:
    name: java-latest-openjdk
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
  tags: wildfly

- name: Install openjdk17 
  package:
    name: java-17-openjdk
    state: present
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: wildfly



- name: add group "jboss"
  group: name={{ wildfly_user }}
  tags: wildfly

- name: add user "jboss"
  user: name={{ wildfly_user }} group={{ wildfly_group }} home={{ wildfly_dir }} createhome=no
  tags: wildfly


- name: Download and extract Wildfly
  unarchive: 
    src: https://github.com/wildfly/wildfly/releases/download/{{ wildfly_version }}/{{ wildfly_package }} 
    dest: "{{ wildfly_install_path }}"
    remote_src: yes
  tags: wildfly

- name: Symlink install directory
  file: src={{ wildfly_install_path }}/{{ wildfly_final }} path={{ wildfly_dir }} state=link
  tags: wildfly

- name: Create management users
  command: /opt/{{ wildfly_final }}/bin/add-user.sh {{ name }} {{ password }} --silent
  tags: wildfly

- name: Change Ownership of Wildfly installation
  file: path={{ wildfly_dir }} owner={{ wildfly_user }} group={{ wildfly_group }} state=directory recurse=yes mode=0755
  tags: wildfly


- name: Setting JAVA_HOME in standalone.conf
  lineinfile:
    path: /opt/{{ wildfly_final }}/bin/standalone.conf
    regexp: '^#JAVA_HOME'
    insertafter: '^#JAVA_HOME'
    line: JAVA_HOME="/usr/lib/jvm/jre"
  tags: wildfly


#- name: Copy Standalone.xml into Wildfly Configuration
#  template:
#    src:  standalone.xml
#    dest: /usr/share/jboss-as/standalone/configuration
#    mode: 0644
#  tags: wildfly


- name: Adding port 8080/tcp for wildfly
  firewalld:
    port: 8080/tcp
    permanent: true
    immediate: true
    state: enabled
  tags: wildfly 


- name: Adding port 9990/tcp for wildfly management console
  firewalld:
    port: 9990/tcp
    permanent: true
    immediate: true
    state: enabled
  tags: wildfly 

- name: Copy wildfly service into systemd 
  template: 
    src: wildfly.service.j2
    dest: /usr/lib/systemd/system/wildfly.service
  tags: wildfly

- name: systemd daemon reload
  systemd: daemon_reload=yes
  tags: wildfly

- name: Enable wildfly at boot and start 
  systemd:
    name: wildfly.service
    state: started
    enabled: True
  tags: wildfly

