
- name: Stopping wildfly service
  systemd: state=stopped name=wildfly
  ignore_errors: True
  tags: wildfly

- name: Remove wildfly directory
  file: path="{{wildfly_install_path}}/{{wildfly_final}}" state=absent
  tags: wildfly

- name: Remove wildfly.zip
  file: path="{{wildfly_install_path}}/{{wildfly_package}}" state=absent
  tags: wildfly

- name: Remove symlink wildfly directory
  file: path="{{wildfly_dir}}" state=absent
  tags: wildfly

- name: Remove wildfly service into systemd and reloading daemon
  file: path=/usr/lib/systemd/system/wildfly.service state=absent
  notify: systemd reload 
  tags: wildfly

- name: Remove the user 'jboss'
  user:
    name: jboss
    state: absent
    remove: yes
  tags: wildfly


- name: Remove the group 'jboss'
  group:
    name: jboss
    state: absent
  tags: wildfly


- name: Remove port 8080/TCP for wildfly
  firewalld:
    port : 8080/tcp
    permanent: true
    immediate: true
    state: disabled
  tags: wildfly


- name: Remove port 9990/TCP management console for wildfly
  firewalld:
    port : 9990/tcp
    permanent: true
    immediate: true
    state: disabled
  tags: wildfly

